<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.11.0rc1 on linux)" generated="20230505 12:02:03.219" rpa="false" schemaversion="3">
<suite id="s1" name="Test" source="/home/plinio/Documentos/IREDE/Estudos/Robot Framework/Test/test.robot">
<test id="s1-t1" name="scenario 1: Test open google website" line="18">
<kw name="open google website">
<kw name="Open Browser">
<arg>https://www.google.com.br/</arg>
<arg>${BROWSER}</arg>
<msg timestamp="20230505 12:02:03.228" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20230505 12:02:03.228" endtime="20230505 12:02:03.228"/>
</kw>
<status status="FAIL" starttime="20230505 12:02:03.227" endtime="20230505 12:02:03.228"/>
</kw>
<kw name="close website">
<status status="NOT RUN" starttime="20230505 12:02:03.228" endtime="20230505 12:02:03.228"/>
</kw>
<status status="FAIL" starttime="20230505 12:02:03.227" endtime="20230505 12:02:03.228">No keyword with name 'Open Browser' found.</status>
</test>
<test id="s1-t2" name="scenario 2: Test open globo website" line="22">
<kw name="open globo website">
<kw name="Open Browser">
<arg>https://g1.globo.com/</arg>
<arg>${BROWSER}</arg>
<msg timestamp="20230505 12:02:03.229" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20230505 12:02:03.229" endtime="20230505 12:02:03.229"/>
</kw>
<status status="FAIL" starttime="20230505 12:02:03.229" endtime="20230505 12:02:03.229"/>
</kw>
<kw name="Close Browser">
<status status="NOT RUN" starttime="20230505 12:02:03.230" endtime="20230505 12:02:03.230"/>
</kw>
<status status="FAIL" starttime="20230505 12:02:03.229" endtime="20230505 12:02:03.230">No keyword with name 'Open Browser' found.</status>
</test>
<status status="FAIL" starttime="20230505 12:02:03.220" endtime="20230505 12:02:03.230"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230505 12:02:03.227" level="ERROR">Error in file '/home/plinio/Documentos/IREDE/Estudos/Robot Framework/Test/test.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /home/plinio/.local/bin
  /usr/lib/python311.zip
  /usr/lib/python3.11
  /usr/lib/python3.11/lib-dynload
  /home/plinio/.local/lib/python3.11/site-packages
  /usr/local/lib/python3.11/dist-packages
  /usr/lib/python3/dist-packages</msg>
</errors>
</robot>
